# Generated by Django 5.0.2 on 2024-05-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacie',
            name='produits',
            field=models.ManyToManyField(to='app1.produit'),
        ),
    ]
