# Generated by Django 5.0.2 on 2024-05-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_pharmacie_produits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='ordonnance_requise',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
