# Generated by Django 5.0.2 on 2024-05-16 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_produit_ordonnance_requise'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacommandes',
            name='pharmacie',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='app1.pharmacie'),
        ),
    ]
