# Generated by Django 5.0.2 on 2024-05-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_livreur_user_alter_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreur',
            name='disponible',
            field=models.BooleanField(default=False),
        ),
    ]
