# Generated by Django 5.0.2 on 2024-05-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_livreur_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreur',
            name='ville',
            field=models.CharField(default='Alger', max_length=100),
        ),
    ]
