# Generated by Django 5.0.2 on 2024-05-16 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_livreur_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacommandes',
            name='livreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.livreur'),
        ),
    ]
