# Generated by Django 5.0.2 on 2024-05-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_patient_commandes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacommandes',
            name='etat',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTE', 'Accepté'), ('EN_COURS_DE_LIVRAISON', 'En cours de livraison'), ('LIVRE', 'Livré')], default='EN_ATTENTE', max_length=200),
        ),
    ]
